package:
  name: histrux
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.26.4
    - pandas >=2.2.3
    - scipy >=1.12.0
    - matplotlib >=3.9.2
    - more-itertools >=10.5.0
    - hoomd >=4.8.2
    - cooler >=0.10.2
    - h5py >=3.11.0
    - gsd >=3.3.2
    - pyvista >=0.44.2
    - scikit-learn >=1.6.0
    - seaborn >=0.13.2

about:
  home: https://github.com/AdixPlaysGames/HiStrux
  license: MIT
  summary: Python package for Hi-C feature extraction and reconstruction
  license_file: LICENSE

extra:
  authors:
    - Adrian Zaręba
    - Wiktor Wierzchowski
